svportal/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.contrib.auth import logout
from django.urls import path,re_path
from svapp.views import (QuizListView,StudentInterestsView,TakenQuizListView,QuizResultsView,
                        QuizChangeListView,QuizCreateView,QuizUpdateView,QuizDeleteView,QuizTeacherResultsView,QuestionDeleteView,
                        AddQuestionsView)
from svapp import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^index/$', views.index),
    url(r'^adm/$', views.adm),
    url(r'^student/$', views.student),
    url(r'^teacher/$', views.teacher),
    url(r'^about/',views.about),
    url(r'^treg/',views.teacher_reg),
    url(r'^tlog/',views.teacher_log),
    url(r'^sreg/',views.student_reg),
    url(r'^slog/', views.student_log),
    url(r'^log/', views.login),
    url(r'^logout/$',views.logout_view),
    url(r'^adds/',views.add_student),
    url(r'^addt/',views.add_teacher),
    url(r'^comment/',views.User_comment_view),
    url(r'^com/',views.Student_comment_view),
    url(r'^comments/',views.comments),
    url(r'^show/', views.show),
    url(r'^sdetails/',views.sdetails),
    url(r'^tdetails/',views.tdetails),
    url(r'^subdetails/', views.subject_details),
    url(r'^subdelete/(?P<id>\d+)/', views.subject_delete),
    url(r'^subupdate/(?P<id>\d+)/', views.subject_update),
    url(r'^dels/(?P<id>\d+)/', views.delete_s),
    url(r'^delt/(?P<id>\d+)/', views.delete_t),
    url(r'^delc/(?P<id>\d+)/', views.delete_c),
    url(r'^delsc/(?P<id>\d+)/', views.delete_sc),
    url(r'^ups/(?P<id>\d+)/',views.StudentUpdate),
    url(r'^update_s/(?P<id>\d+)/',views.S_Update),
    url(r'^update_t/(?P<id>\d+)/',views.T_Update),
    url(r'^upt/(?P<id>\d+)/',views.TeacherUpdate),
    url(r'^search_s/',views.Search_Student),
    url(r'^search_t/',views.Search_Teacher),
    url(r'^search_a/',views.Search_Assessments),
    url(r'^search_q/',views.Search_Quiz),
    url(r'^easy/',views.easy),
    url(r'^medium/',views.medium),
    url(r'^hard/',views.hard),
    url(r'^write/', views.write),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^addprofile/(?P<id>\d+)/',views.ProfileUpdate, name='addprofile'),
    url(r'^quiz_list/',QuizListView.as_view(), name='quiz_list'),
    url(r'^interests/',StudentInterestsView.as_view(), name='student_interests'),
    url(r'^taken/', TakenQuizListView.as_view(), name='taken_quiz_list'),
    url(r'^quiztake/(?P<pk>\d+)/$', views.take_quiz, name='take_quiz'),
    url(r'^quiz/(?P<pk>\d+)/studentresults/$', QuizResultsView.as_view(), name='student_quiz_results'),

    url(r'^quiz_change_list/', QuizChangeListView.as_view(), name='quiz_change_list'),
    url(r'^quiz/add/', QuizCreateView.as_view(), name='quiz_add'),
    url(r'^quiz/(?P<pk>\d+)/$', QuizUpdateView.as_view(), name='quiz_change'),
    url(r'^quiz/(?P<pk>\d+)/delete/$', QuizDeleteView.as_view(), name='quiz_delete'),
    url(r'^quiz/(?P<pk>\d+)/results/$', QuizTeacherResultsView.as_view(), name='quiz_results'),
    url(r'^quiz/(?P<pk>\d+)/question/add/$', views.question_add, name='question_add'),
    url(r'^quiz/(?P<quiz_pk>\d+)/question/(?P<question_pk>\d+)/$', views.question_change, name='question_change'),
    url(r'^quiz/(?P<quiz_pk>\d+)/question/(?P<question_pk>\d+)/delete/$', QuestionDeleteView.as_view(), name='question_delete'),

    url(r'^addquestions/', AddQuestionsView.as_view(), name='addquestions'),
    url(r'^addsubjects/',views.subject_add, name='addsubjects'),
    url(r'^qdelete/(?P<idd>.*)/',views.question_delete, name='q_delete'),

] +static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

svapp/models.py
# Create your models here.
from django.db import models
from django.contrib import auth
from django.contrib.auth import get_user_model
from django.utils.html import escape, mark_safe
from django.core.validators import RegexValidator
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class UserManager(BaseUserManager):
    def create_user(self, email,rollnumber=None,phone=None,username=None,profile=None,branch=None,gender=None, year=None, section=None, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        if not password:
            raise ValueError('User must have an Password')
        user = self.model(
            email=self.normalize_email(email),

        )
        user.username=username
        user.year=year
        user.section=section
        user.gender=gender
        user.branch=branch
        user.phone=phone
        user.profile=profile
        user.rollnumber=rollnumber
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,

        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_studentuser(self, email,password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,

        )
        user.is_student = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.is_student = True
        user.admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )

    username=models.CharField(
    max_length=30,
    null=True,blank=True
     )
    g_choices=(
    ('Male','Male'),
    ('Female','Female'),
    ('Others','Others'),
    )
    gender=models.CharField(max_length=10,null=True,blank=True,choices=g_choices)
    y_choices=(('1st','1st'),
    ('2nd','2nd'),
    ('3rd','3rd'),
    ('4th','4th'),)
    year=models.CharField(max_length=10,null=True,blank=True,choices=y_choices)
    s_choices=(
    ('Section A','Section A'),
    ('Section B','Section B'),
    ('Section C','Section C'),
    ('Section D','Section D'),)
    section=models.CharField(max_length=10,null=True,blank=True,choices=s_choices)
    b_choices=(
    ('M.C.A','M.C.A'),
    ('M.B.A','M.B.A'),
    ('E.C.E','E.C.E'),
    ('E.E.E','E.E.E'),
    ('C.S.E','C.S.E'),
    ('IT','IT'      ),
    ('CIVIL','CIVIL'),
    )
    branch=models.CharField(max_length=10,null=True,blank=True,choices=b_choices)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,12}$',
                                 message="Phone number must be entered in the define format")
    phone=models.CharField(validators=[phone_regex], max_length=10,unique=True,null=True,blank=True)
    rollnumber=models.CharField(max_length=10,null=True,blank=True,unique=True)
    profile = models.ImageField(upload_to='', max_length=255,null=True,blank=True)
    is_student=models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False) # a admin user; non super-user
    admin = models.BooleanField(default=False)
    datejoined = models.DateTimeField(default=timezone.now)
     # a superuser
    # notice the absence of a "Password field", that is built in.

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [] # Email & Password are required by default.

    objects=UserManager()


    def get_username(self):

        return self.email

    def get_rollnumber(self):

        return self.email

    def get_phone(self):

        return self.email

    def get_branch(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):
            # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff


    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

    @property
    def is_active(self):
        "Is the user active?"
        return self.active


class Subject(models.Model):
    name = models.CharField(max_length=50)
    c_choices=(
        ('#007bff','#007bff'),
        ('#EC407A','#EC407A'),
        ('#FF5733','#FF5733'),
        ('#2ECC71','#2ECC71'),
        ('#7D3C98','#7D3C98'),
        ('#1B4F72','#1B4F72'),
        ('#F7DC6','#F7DC6'),
    )
    color = models.CharField(max_length=100, choices=c_choices)

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)


class Quiz(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quizzes')
    name = models.CharField(max_length=255)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='quizzes')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    d_choices=(
        ('Easy','Easy'),
        ('Medium','Medium'),
        ('Hard','Hard'),
    )
    difficulty = models.CharField(max_length=10,blank=False,choices=d_choices,default='Easy')
    text = models.TextField('Question', max_length=3000)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField('Answer', max_length=255)
    is_correct = models.BooleanField('Correct answer', default=False)

    def __str__(self):
        return self.text


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    quizzes = models.ManyToManyField(Quiz, through='TakenQuiz')
    interests = models.ManyToManyField(Subject, related_name='interested_students')

    # User reputation score.
    score = models.IntegerField(default=0)

    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    def __str__(self):
        return self.user.username


class TakenQuiz(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='taken_quizzes')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='taken_quizzes')
    score = models.IntegerField()
    percentage = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)


class StudentAnswer(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='quiz_answers')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='+')


class User_comments(models.Model):
    username=models.CharField(max_length=225)
    email=models.EmailField(max_length=225,unique=True)
    subject = models.CharField(max_length=3000)
    message=models.TextField(max_length=3000)
    date= models.DateTimeField(default=timezone.now)

class Student_comments(models.Model):
    username=models.CharField(max_length=225)
    rollnumber=models.CharField(max_length=10,unique=True)
    subject = models.CharField(max_length=3000)
    message=models.TextField(max_length=3000)
    date= models.DateTimeField(default=timezone.now)

templates/sapp/Student_comments.html
<div class="col-md-8 col-lg-9">
  <form method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-lg-5">
        <div class="form-group">
          <input class="form-control" name="username" type="text" placeholder="Enter your name">
        </div>
        <div class="form-group">
          <input class="form-control" name="rollnumber"  type="text" placeholder="Enter Rollnumber">
        </div>
        <div class="form-group">
          <input class="form-control" name="subject"  type="text" placeholder="Enter Subject">
        </div>
      </div>
      <div class="col-lg-7">
        <div class="form-group">
            <textarea type="text" class="form-control different-control w-100" name="message" cols="30" rows="5" placeholder="Enter Message"></textarea>
          </div>
        </div>
      </div>
      <div class="form-group text-center text-md-right mt-3">
        <button type="submit" class="button button-contactForm">Send Message</button>
      </div>
    </form>
  </div>

templates/sapp/about.html
<!DOCTYPE html>
{% extends 'svapp/student1.html' %}
{% load staticfiles %}
{% block body_block %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>SV Assessment Portal</title>

  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="{% static "sapp/v1/bootstrap/css/bootstrap.min.css" %}">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="{% static "sapp/f1/font-awesome-4.7.0/css/font-awesome.min.css" %}">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="{% static "sapp/v1/animate/animate.css" %}">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="{% static "sapp/v1/select2/select2.min.css" %}">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="{% static "sapp/v1/perfect-scrollbar/perfect-scrollbar.css" %}">
  <!--===============================================================================================-->
  	<link rel="stylesheet" type="text/css" href="{% static "sapp/css/t2.css" %}">
  	<link rel="stylesheet" type="text/css" href="{% static "sapp/css/t.css" %}">
  <!--===============================================================================================-->
{% include 'cdn.html' %}
</head>
<body>
  <div class="container" align='center' style="margin-top:20px;">
  <h2 style="color:navy; padding-top:40px;"><img class="author_img rounded-circle" src="{% static "images/svce2.png" %}" >  SV College of Engineering </h2>
  <p>   Education For Better Society</p>
  </div>

 <section class="blog_area single-post-area section-margin--medium">
   <div class="container">
     <div class="row">
         <!-- <div class="col-lg-8 posts-list"> -->

             <div class="single-post row">
                 <div class="col-lg-12">
                     <div class="feature-img">
                       <div class="view overlay zoom">
                         <img class="img-fluid  z-depth-4 rounded" src="{% static "images/Home_2.jpg" %}" alt="">
                       </div>
                     </div>
                 </div>
                 <div class="col-lg-3  col-md-3">
                     <div class="blog_info text-right">
                         <div class="post_tag">
                             <a href="#">Studies</a>
                             <a class="active" href="#">Technology,</a>
                             <a href="#">Sports</a>
                             <a href="#">Lifestyle</a>
                         </div>
                         <ul class="blog_meta list">
                             <li>
                                 <a href="#">Murali Krishna
                                     <i class="lnr lnr-user"></i>
                                 </a>
                             </li>
                             <li>
                                 <a href="#">5 Mar, 2020
                                     <i class="lnr lnr-calendar-full"></i>
                                 </a>
                             </li>
                             <li>
                                 <a href="#">1.2M Views
                                     <i class="lnr lnr-eye"></i>
                                 </a>
                             </li>
                             <li>
                                 <a href="#">06 Comments
                                     <i class="lnr lnr-bubble"></i>
                                 </a>
                             </li>
                         </ul>

                     </div>
                 </div>
                 <div class="col-lg-9 col-md-9 blog_details">
                     <h2>SV College of Engineering, Tirupati</h2>
                     <p class="excert">
                         At SV Colleges, we empower our students to achieve professional and personal success by providing a comprehensive and supportive educational experience, fostering critical thinking and encouraging lifelong learning.
                     </p>
                     <p>
                        Our career-focused programs and services provide the knowledge and skills necessary to be successful in the fast-paced world. Irrespective of the course, we make sure that our students get the real-world learning experience that helps in achieving their future goals.
                     </p>
                     <p>
                      <strong>SV Colleges</strong> is a community where - care, support and mutual respect flourishes. Our students are our first priority. We welcome you to join us and become yet another SV Colleges’ success story.
                     </p>
                 </div>
                 <div class="col-lg-12">
                     <div class="quotes">
                      <strong>Council for Social Development </strong>(the umbrella organization of SV Colleges) was founded in 1981 based on the firm belief that education, especially higher education, provides a critical pathway to leadership development, economic progress, and social and political equality.
                     </div>
                     <div class="row">
                         <div class="col-6">
                             <img class="img-fluid" src="img/blog/post-img1.jpg" alt="">
                         </div>
                         <div class="col-6">
                             <img class="img-fluid" src="img/blog/post-img2.jpg" alt="">
                         </div>
                     </div>
                    <h2 style="padding-top:50px; padding-bottom:50px;">Colleges Data:</h2>
                     <!-- <section class="section-margin"> -->
                   		<div class="container" align="center">
                   		<div class="limiter" >
                         <table class="table">
                             <thead align="center">
                               <tr class="row100 head " style="background-color:#FFFFE0;">
                                 <th> <h3>#</h3> </th>
                                 <th><h3>Code</h3></th>
                                 <th><h3>Our Institutions</h3></th>
                                 <th><h3>Estd.</h3></th>
                               </tr>
                             </thead>
                       		<tbody align="center">
                            <tr>
                              <td><h5>1</h5></td>
                              <td><h5>SVCE</h5></td>
                              <td><h5>SV College of Engineering, Tirupati</h5></td>
                              <td><h5>2007</h5></td>
                            </tr>
                            <tr>
                              <td><h5>2</h5></td>
                              <td><h5>SVEC</h5></td>
                              <td><h5>SV Engineering of College, Tirupati</h5></td>
                              <td><h5>2019</h5></td>
                            </tr>
                            <tr>
                              <td><h5>3</h5></td>
                              <td><h5>SVDC</h5></td>
                              <td><h5>SV Degree College, Kadapa</h5></td>
                              <td><h5>1981</h5></td>
                            </tr>
                            <tr>
                              <td><h5>4</h5></td>
                              <td><h5>SVCK</h5></td>
                              <td><h5>SV College of Engineering, Kadapa</h5></td>
                              <td><h5>2016</h5></td>
                            </tr>
                       		</tbody>
                           </table>
                   	</div>
                 </div>
               <!-- </section> -->
             </div>
           <!-- </div> -->
       <!-- </div> -->
    </div>
</section>

<section class="section-margin">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-lg-3 mb-4 mb-md-0">
        <div class="media contact-info">
          <span class="contact-info__icon"><i class="ti-home"></i></span>
          <div class="media-body">
            <h3>SV Engineering Colleges-Tirupati</h3>
            <p>Santa monica bullevard</p>
          </div>
        </div>
        <div class="media contact-info">
          <span class="contact-info__icon"><i class="ti-headphone"></i></span>
          <div class="media-body">
            <h3><a href="tel:454545654">00 (440) 9865 562</a></h3>
            <p>Mon to Fri 9am to 6pm</p>
          </div>
        </div>
        <div class="media contact-info">
          <span class="contact-info__icon"><i class="ti-email"></i></span>
          <div class="media-body">
            <h3><a href="#">svce@svcolleges.edu.in</a></h3>
            <p>Send us your query anytime!</p>
          </div>
        </div>
      </div>
      {% include 'sapp/Student_comments.html' %}
      </div>
  </div>
</section>


<!--===============================================================================================-->
	<script src="{% static "sapp/v1/jquery/jquery-3.2.1.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "sapp/v1/bootstrap/js/popper.js" %}"></script>
	<script src="{% static "sapp/v1/bootstrap/js/bootstrap.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "sapp/v1/select2/select2.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "sapp/v1/perfect-scrollbar/perfect-scrollbar.min.js" %}"></script>
	<script>
		$('.js-pscroll').each(function(){
			var ps = new PerfectScrollbar(this);

			$(window).on('resize', function(){
				ps.update();
			})
		});


	</script>
<!--===============================================================================================-->
	<script src="{% static "sapp/js/t.js" %}"></script>

</body>
</html>
{% endblock %}

templates/sapp/addt.html
<!DOCTYPE html>
{% extends 'svapp/a&t.html' %}
{% load staticfiles %}
{% block body_block %}
<head>
	<meta charset="utf-8">
	<title>SV Colleges</title>
	<!-- Mobile Specific Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- Font-->
	<link rel="stylesheet" type="text/css" href="{% static "sapp/css/montserrat-font.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "sapp/fonts/material/css/material-design-iconic-font.min.css" %}">
	<!-- Main Style Css -->
    <link rel="stylesheet" href="{% static "sapp/css/q2.css"  %}">
</head>

	<div class="page-content">
		<div class="form-v10-content">
			<form class="form-detail" method="post" id="myform">
				{% csrf_token %}
				<div class="form-right">
					<h2>Add Teacher</h2>
          <div class="form-row">
            <input type="text" name="username" class="" id="Name" placeholder="Teacher Name" required>
          </div>
					<div class="form-row">
						<select name="branch" required>
						    <option disabled="disabled" selected="selected">Branch</option>
								<option name="M.C.A">M.C.A</option>
						    <option name="M.B.A">M.B.A</option>
						    <option name="E.C.E">E.C.E</option>
								<option name="E.E.E">E.E.E</option>
								<option name="C.S.E">C.S.E</option>
								<option name="CIVIL">CIVIL</option>
								<option name="IT">IT</option>
						</select>
						<span class="select-btn">
						  	<i class="zmdi zmdi-chevron-down"></i>
						</span>
					</div>
					<div class="form-row">
						<select name="gender" required>
              <option disabled="disabled" selected="selected">Gender</option>
              <option name="Male">Male</option>
              <option name="Female">Female</option>
              <option name="Others">Other</option>
						</select>
						<span class="select-btn">
								<i class="zmdi zmdi-chevron-down"></i>
						</span>
					</div>
					<div class="form-row">
						<input type="number" name="phone" class="Phone" id="Phone" placeholder="Phone" required>
					</div>
					<div class="form-row">
						<input type="email" name="email" class="Email" id="Email" placeholder="Email" required>
					</div>
          <div class="form-row">
						<input type="password" name="password" class="password" id="password" placeholder="Password" required>
					</div>
					<div class="form-row">
						<input type="password" name="password1" class="password" id="password" placeholder="Confirm Password" required>
					</div>
					{% for message in messages %}
					<div class="alert {{ message.tags }} alert-dismissible" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
						{{ message }}
						</div>
						{% endfor %}
					<div class="form-row-last">
						<input type="submit" name="register" class="register" value="Add">
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

templates/sapp/comments.html
<!DOCTYPE html>
{% extends 'svapp/a&t.html' %}
{%load staticfiles%}
{% block body_block %}
<head>
  <style media="screen">
    body{
    background:url("{% static "images/36.jpg" %}");
    background-image: no-repeat;
    background-image: cover;
    }
    h2{
      color:navy;
    }
      .card{
        padding-bottom:30px;
        height: auto;
        width: 60%;
      }
      .card-text{
        margin-bottom: 10px;
      }
      .continer{
        padding-left: 300px;
        align-content: flex-end;
      }
      .btn-danger{
        color: navy;
      }
      .card-header{
        padding-bottom:10px;
      }
      .btn {
        line-height: 38px;
        display: inline-block;
        padding: 0 20px;
        cursor: pointer;
        font-family: 'Montserrat', sans-serif;
        color: #FFFFFF;
        -webkit-transition: all 0.4s ease;
        -o-transition: all 0.4s ease;
        -moz-transition: all 0.4s ease;
        transition: all 0.4s ease;
        font-size: 15px;
        font-weight: 500;
        width: 120px;
      }

      .btn--radius {
        -webkit-border-radius: 3px;
        -moz-border-radius: 20px;
        border-radius:50%;
      }

      .btn--green {
        background: navy;
      }

      .btn--green:hover {
        background: blue;
      }
      .ti-trash {
        padding-left:0px;
        size:100px;
        padding-bottom:25px;
      }
  </style>
  <link rel="stylesheet" href="{% static "sapp/css/m1.css" %}">
</head>

<section class="section-margin">
{% if comment_list %}
<div class="continer">
  <div class="row">
  <div class="col-sm-6">
    <h2>Teachers:</h2>
    <div class="card shadow p-3 mb-5 bg-white rounded">
      <div class="card-body">
        {% for comment in comment_list %}
        <h3 class="card-header" style="color:navy;">{{comment.username}} </h3>
        <h4 class="card-title">{{comment.email}} </h4>
        <h3 class="card-title">{{comment.subject}}</h3>
        <p class="card-text">{{comment.message}}</p>
        <div align="right">
          {{comment.date}} &nbsp<a href="/delc/{{comment.id}}"><i style="color:navy;" class="fas fa-trash"></i></a>
        </div>

        {% endfor %}
      </div>
    </div>
  </div>
{% endif %}

{% if student_list %}
  <div class="col-sm-6">
    <h2>Students:</h2>
    <div class="card shadow p-3 mb-5 bg-white rounded">
      <div class="card-body">
        {% for s_comment in student_list %}
        <h3 class="card-header" style="color:navy;">{{s_comment.username}}</h3>
        <h4 class="card-title">{{s_comment.rollnumber}}</h4>
        <h3 class="card-title">{{s_comment.subject}}</h3>
        <p class="card-text">{{s_comment.message}}</p>
        <div align="right">
          {{s_comment.date}} &nbsp<a href="/delsc/{{s_comment.id}}"><i style="color:navy;" class="fas fa-trash"></i></a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
</div>
</section>
{% endif %}
{% endblock %}

templates/sapp/update_student.html
<!DOCTYPE html>
{% extends 'svapp/a&t.html' %}
{% load staticfiles %}
{% block body_block %}
{% load crispy_forms_tags crispy_forms_filters %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  {% include 'cdn.html' %}
  </head>
<body>
{% include 'messages.html' %}
<div class="container" style="margin-top:50px;">
  <div class="jumbotron">
  <h2 class="mb-3">User Profile :</h2>
  <div class="col-md-6 col-md-8 col-12">
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn--radius btn-outline-success">Save</button>
    <a href="/sdetails" class="btn btn--radius btn-outline-secondary" role="button">Nevermind</a>
  </form>
  </div>
</div>
</div>
</body>
</html>
{% endblock %}