svportal/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.contrib.auth import logout
from django.urls import path,re_path
from svapp.views import (QuizListView,StudentInterestsView,TakenQuizListView,QuizResultsView,
                        QuizChangeListView,QuizCreateView,QuizUpdateView,QuizDeleteView,QuizTeacherResultsView,QuestionDeleteView,
                        AddQuestionsView)
from svapp import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^index/$', views.index),
    url(r'^adm/$', views.adm),
    url(r'^student/$', views.student),
    url(r'^teacher/$', views.teacher),
    url(r'^about/',views.about),
    url(r'^treg/',views.teacher_reg),
    url(r'^tlog/',views.teacher_log),
    url(r'^sreg/',views.student_reg),
    url(r'^slog/', views.student_log),
    url(r'^log/', views.login),
    url(r'^logout/$',views.logout_view),
    url(r'^adds/',views.add_student),
    url(r'^addt/',views.add_teacher),
    url(r'^comment/',views.User_comment_view),
    url(r'^com/',views.Student_comment_view),
    url(r'^comments/',views.comments),
    url(r'^show/', views.show),
    url(r'^sdetails/',views.sdetails),
    url(r'^tdetails/',views.tdetails),
    url(r'^subdetails/', views.subject_details),
    url(r'^subdelete/(?P<id>\d+)/', views.subject_delete),
    url(r'^subupdate/(?P<id>\d+)/', views.subject_update),
    url(r'^dels/(?P<id>\d+)/', views.delete_s),
    url(r'^delt/(?P<id>\d+)/', views.delete_t),
    url(r'^delc/(?P<id>\d+)/', views.delete_c),
    url(r'^delsc/(?P<id>\d+)/', views.delete_sc),
    url(r'^ups/(?P<id>\d+)/',views.StudentUpdate),
    url(r'^update_s/(?P<id>\d+)/',views.S_Update),
    url(r'^update_t/(?P<id>\d+)/',views.T_Update),
    url(r'^upt/(?P<id>\d+)/',views.TeacherUpdate),
    url(r'^search_s/',views.Search_Student),
    url(r'^search_t/',views.Search_Teacher),
    url(r'^search_a/',views.Search_Assessments),
    url(r'^search_q/',views.Search_Quiz),
    url(r'^easy/',views.easy),
    url(r'^medium/',views.medium),
    url(r'^hard/',views.hard),
    url(r'^write/', views.write),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^addprofile/(?P<id>\d+)/',views.ProfileUpdate, name='addprofile'),
    url(r'^quiz_list/',QuizListView.as_view(), name='quiz_list'),
    url(r'^interests/',StudentInterestsView.as_view(), name='student_interests'),
    url(r'^taken/', TakenQuizListView.as_view(), name='taken_quiz_list'),
    url(r'^quiztake/(?P<pk>\d+)/$', views.take_quiz, name='take_quiz'),
    url(r'^quiz/(?P<pk>\d+)/studentresults/$', QuizResultsView.as_view(), name='student_quiz_results'),

    url(r'^quiz_change_list/', QuizChangeListView.as_view(), name='quiz_change_list'),
    url(r'^quiz/add/', QuizCreateView.as_view(), name='quiz_add'),
    url(r'^quiz/(?P<pk>\d+)/$', QuizUpdateView.as_view(), name='quiz_change'),
    url(r'^quiz/(?P<pk>\d+)/delete/$', QuizDeleteView.as_view(), name='quiz_delete'),
    url(r'^quiz/(?P<pk>\d+)/results/$', QuizTeacherResultsView.as_view(), name='quiz_results'),
    url(r'^quiz/(?P<pk>\d+)/question/add/$', views.question_add, name='question_add'),
    url(r'^quiz/(?P<quiz_pk>\d+)/question/(?P<question_pk>\d+)/$', views.question_change, name='question_change'),
    url(r'^quiz/(?P<quiz_pk>\d+)/question/(?P<question_pk>\d+)/delete/$', QuestionDeleteView.as_view(), name='question_delete'),

    url(r'^addquestions/', AddQuestionsView.as_view(), name='addquestions'),
    url(r'^addsubjects/',views.subject_add, name='addsubjects'),
    url(r'^qdelete/(?P<idd>.*)/',views.question_delete, name='q_delete'),

] +static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

svapp/models.py
# Create your models here.
from django.db import models
from django.contrib import auth
from django.contrib.auth import get_user_model
from django.utils.html import escape, mark_safe
from django.core.validators import RegexValidator
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class UserManager(BaseUserManager):
    def create_user(self, email,rollnumber=None,phone=None,username=None,profile=None,branch=None,gender=None, year=None, section=None, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        if not password:
            raise ValueError('User must have an Password')
        user = self.model(
            email=self.normalize_email(email),

        )
        user.username=username
        user.year=year
        user.section=section
        user.gender=gender
        user.branch=branch
        user.phone=phone
        user.profile=profile
        user.rollnumber=rollnumber
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,

        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_studentuser(self, email,password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,

        )
        user.is_student = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.is_student = True
        user.admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )

    username=models.CharField(
    max_length=30,
    null=True,blank=True
     )
    g_choices=(
    ('Male','Male'),
    ('Female','Female'),
    ('Others','Others'),
    )
    gender=models.CharField(max_length=10,null=True,blank=True,choices=g_choices)
    y_choices=(('1st','1st'),
    ('2nd','2nd'),
    ('3rd','3rd'),
    ('4th','4th'),)
    year=models.CharField(max_length=10,null=True,blank=True,choices=y_choices)
    s_choices=(
    ('Section A','Section A'),
    ('Section B','Section B'),
    ('Section C','Section C'),
    ('Section D','Section D'),)
    section=models.CharField(max_length=10,null=True,blank=True,choices=s_choices)
    b_choices=(
    ('M.C.A','M.C.A'),
    ('M.B.A','M.B.A'),
    ('E.C.E','E.C.E'),
    ('E.E.E','E.E.E'),
    ('C.S.E','C.S.E'),
    ('IT','IT'      ),
    ('CIVIL','CIVIL'),
    )
    branch=models.CharField(max_length=10,null=True,blank=True,choices=b_choices)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,12}$',
                                 message="Phone number must be entered in the define format")
    phone=models.CharField(validators=[phone_regex], max_length=10,unique=True,null=True,blank=True)
    rollnumber=models.CharField(max_length=10,null=True,blank=True,unique=True)
    profile = models.ImageField(upload_to='', max_length=255,null=True,blank=True)
    is_student=models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False) # a admin user; non super-user
    admin = models.BooleanField(default=False)
    datejoined = models.DateTimeField(default=timezone.now)
     # a superuser
    # notice the absence of a "Password field", that is built in.

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [] # Email & Password are required by default.

    objects=UserManager()


    def get_username(self):

        return self.email

    def get_rollnumber(self):

        return self.email

    def get_phone(self):

        return self.email

    def get_branch(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):
            # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff


    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

    @property
    def is_active(self):
        "Is the user active?"
        return self.active


class Subject(models.Model):
    name = models.CharField(max_length=50)
    c_choices=(
        ('#007bff','#007bff'),
        ('#EC407A','#EC407A'),
        ('#FF5733','#FF5733'),
        ('#2ECC71','#2ECC71'),
        ('#7D3C98','#7D3C98'),
        ('#1B4F72','#1B4F72'),
        ('#F7DC6','#F7DC6'),
    )
    color = models.CharField(max_length=100, choices=c_choices)

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = '<span class="badge badge-primary" style="background-color: %s">%s</span>' % (color, name)
        return mark_safe(html)


class Quiz(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='quizzes')
    name = models.CharField(max_length=255)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='quizzes')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    d_choices=(
        ('Easy','Easy'),
        ('Medium','Medium'),
        ('Hard','Hard'),
    )
    difficulty = models.CharField(max_length=10,blank=False,choices=d_choices,default='Easy')
    text = models.TextField('Question', max_length=3000)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField('Answer', max_length=255)
    is_correct = models.BooleanField('Correct answer', default=False)

    def __str__(self):
        return self.text


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    quizzes = models.ManyToManyField(Quiz, through='TakenQuiz')
    interests = models.ManyToManyField(Subject, related_name='interested_students')

    # User reputation score.
    score = models.IntegerField(default=0)

    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('text')
        return questions

    def __str__(self):
        return self.user.username


class TakenQuiz(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='taken_quizzes')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='taken_quizzes')
    score = models.IntegerField()
    percentage = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)


class StudentAnswer(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='quiz_answers')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='+')


class User_comments(models.Model):
    username=models.CharField(max_length=225)
    email=models.EmailField(max_length=225,unique=True)
    subject = models.CharField(max_length=3000)
    message=models.TextField(max_length=3000)
    date= models.DateTimeField(default=timezone.now)

class Student_comments(models.Model):
    username=models.CharField(max_length=225)
    rollnumber=models.CharField(max_length=10,unique=True)
    subject = models.CharField(max_length=3000)
    message=models.TextField(max_length=3000)
    date= models.DateTimeField(default=timezone.now)

templates/teachers/add questions.html
<!DOCTYPE html>
{% extends 'svapp/a&t.html' %}
{% load staticfiles %}
{% block body_block %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
  {% include 'cdn.html' %}
  </head>
  <body>
    {% include 'messages.html' %}
    <div class="container" style="margin-bottom:100px;">
			<h2 style="margin-bottom:50px;">Profile :</h2>
	    <div class="row">
	    <div class="col s12 m12 l12">
	        <div class="card horizontal card-image profilecard z-depth-3 grey-text text-darken-3">
						{% if user.profile %}
	        <div class="card-image">
	            <img class="author_img rounded-circle" src="{{user.profile.url}}" style="border-radius: 50%; height:120px; width:120px; margin-left:4rem; margin-top:2rem; margin-bottom:1rem">
          </div>
					{% else %}
					<div class="card-image">
	          <img class="author_img rounded-circle" src="{% static "L/images/svce6.png" %}" style="margin-left:4rem; margin-top:2rem; margin-bottom:1rem">
	        </div>
					{% endif %}
      <div class="card-stacked">
      <div class="card-content">
      <div class="row">
          <div class="col s8 l4 offset-s2" align="center">
                  <h4 class="card-title" style="color:navy; text-transform: uppercase;">{{user.username}}</h4>
                  <h5 class="card-title" style="text-transform: uppercase; color:navy;">{{user.branch}}</h5>
              </div>
              <div class="col s6 l2"  align="center">
                  <h4 class="card-title" style="color:navy;">{{quizzes.count}}</h4>
                  <span style="color:navy;">No of Assessments</span>
              </div>
							<div class="col s6 l2" align="center">
                  <h4 class="card-title" style="color:navy;">{{user.email}}</h4>
                  <span style="color:navy;">Email</span>
              </div>
              <div class="col s6 l2" align="center">
                  <h4 class="card-title" style="color:navy;">{{user.phone}}</h4>
                  <span style="color:navy;">Phone</span>
              </div>
          </div>
      </div>
      {% if user.admin == True %}
      <div class="modal-footer">
				<div align="right" style="margin:10px;">
					<a class="btn btn--radius btn-success btn-md" href="{% url 'addsubjects' %}">Add Subjects</a>
          <a class="btn btn--radius btn-info btn-md" href="{% url 'addprofile' user.id %}">Add Profile Pic</a>
          <a class="btn btn--radius btn-warning btn-md" href="/upt/{{user.id}}">Profile Edit</a>
          <a class="btn btn--radius btn-danger btn-md" href="/subdetails">Edit Subjects</a>
        </div>
		</div>
      {% else %}
      <div class="modal-footer">
				<div align="right" style="margin:10px;">
					<a class="btn btn--radius btn-success btn-md" href="/upt/{{user.id}}">Profile Edit</a>
          <a class="btn btn--radius btn-default btn-md" href="{% url 'addprofile' user.id %}">Add Profile Pic</a>
        </div>
		</div>
      {% endif %}
  </div>
  </div>
</div>
</div>
</div>

<div class="container" style="margin-bottom:150px;">
	<h2 style="margin-bottom:50px;">Assessments :</h2>
  <div class="col-md-6 col-md-8 col-12">
  <form action="/search_a/" method="post" >
    {% csrf_token %}
    <div class="input-group mb-3">
      <input  type="text" name="srh" class="form-control"  placeholder="Search Your Assessments" aria-label="Search">
    <div class="input-group-append">
    <button type="submit" class="btn btn-outline-info btn--radius btn-sm my-0">Search</button>
    </div>
    </div>
  </form>
  </div>
	<div class="row">
	{% for quiz in quizzes %}
	<div class="card shadow-lg" style="width: 18rem; margin:41px;">
  <div class="card-body">
    <h3 class="card-title">{{ quiz.name }}</h3>
		<h6 class="card-title">Subject: {{ quiz.subject.get_html_badge }} </h6>
		<h6 class="card-title">Questions: {{ quiz.questions_count }}</h6>
		<h6 class="card-title">Taken: {{ quiz.taken_count }}</h6>
     <div align="right">
       <!-- <a href="{% url 'question_add' quiz.pk %}" class="btn btn--radius btn-info btn-sm">Add Questions</a>  -->
     	<a href="{% url 'quiz_change' quiz.pk %}" class="btn btn--radius btn-info btn-sm">Add Questions</a>
     </div>
  </div>
	</div>
	{% endfor %}
</div>
</div>

<section class="section-margin">
  {% if sr %}
  <div class="container">
    <div class="row">
	{% for quiz in sr %}
	<div class="card shadow-lg" style="width: 18rem; margin:41px;">
  <div class="card-body">
    <h3 class="card-title">{{ quiz.name }}</h3>
		<h6 class="card-title">Subject: {{ quiz.subject.get_html_badge }} </h6>
		<h6 class="card-title">Questions: {{ quiz.questions_count }}</h6>
		<h6 class="card-title">Taken: {{ quiz.taken_count }}</h6>
     <div align="right">
     	<a href="{% url 'question_add' quiz.pk %}" class="btn btn--radius btn-info btn-sm">Add Questions</a>
     </div>
  </div>
	</div>
	{% endfor %}
  </div>
  </div>
 {% endif %}
</section>
</body>
</html>
{% endblock %}

templates/teachers/add subjects.html
<!DOCTYPE html>
{% extends 'svapp/a&t.html' %}
{% load staticfiles %}
{% block body_block %}
{% load crispy_forms_tags crispy_forms_filters %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
  {% include 'cdn.html' %}
  </head>
<body>
{% include 'messages.html' %}
<div class="container" style="margin-top:50px;">
  <div class="jumbotron">
  <h2 class="mb-3">Add a new Subjects</h2>
  <p class="lead">Add first the text of the subjects. In the next step you will be able to add the color.</p>
  <div class="col-md-6 col-md-8 col-12">
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn--radius btn-outline-success">Save</button>
    <a href="{% url 'addquestions' %}" class="btn btn--radius btn-outline-secondary" role="button">Nevermind</a>
  </form>
  </div>
</div>
</div>
</body>
</html>
{% endblock %}

templates/teachers/question_add_form.html
<!DOCTYPE html>
{% extends 'svapp/a&t.html' %}
{% load staticfiles %}
{% block body_block %}
{% load crispy_forms_tags crispy_forms_filters %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
  {% include 'cdn.html' %}
  </head>
<body>
{% include 'messages.html' %}
<div class="container" style="margin-top:90px;">
  <div class="jumbotron">
  <h2 class="mb-3">Add a new question</h2>
  <p class="lead">Add first the text of the question. In the next step you will be able to add the possible answers.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn--radius btn-outline-success">Save</button>
    <a href="{% url 'quiz_change' quiz.pk %}" class="btn btn--radius btn-outline-secondary" role="button">Nevermind</a>
  </form>
</div>
</div>
</body>
</html>
{% endblock %}

templates/teachers/question_change_form.html
<!DOCTYPE html>
{% extends 'svapp/a&t.html' %}
{% load staticfiles %}
{% block body_block %}
{% load crispy_forms_tags crispy_forms_filters %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% include 'cdn.html' %}
  </head>
<body>
  {% include 'messages.html' %}
  <div class="container" style="margin-top:90px;">
    <div class="jumbotron">
    <h2 class="breadcrumb-item"><a href="{% url 'quiz_change' quiz.pk %}">{{ quiz.name }}</a></h2>
  <h2 class="mb-3">{{ question.txt }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      <div class="card-body">
        <div class="row">
          <div class="col-8">
            <strong>Answers</strong>
          </div>
          <div class="col-2">
            <strong>Correct?</strong>
          </div>
          <div class="col-2">
            <strong>Delete?</strong>
          </div>
        </div>
      </div>
      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}
      <div class="list-group list-group-flush list-group-formset">
        {% for form in formset %}
          <div class="list-group-item">
            <div class="row">
              <div class="col-8">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.text|as_crispy_field }}
                {% if form.instance.pk and form.text.value != form.instance.text %}
                <p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.text }}</small></p>
                {% endif %}
              </div>
              <div class="col-2">
                {{ form.is_correct }}
              </div>
              <div class="col-2">
                {% if form.instance.pk %}
                  {{ form.DELETE }}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <p>
      <small class="form-text text-muted">Your question may have at least <strong>2</strong> answers and maximum <strong>5</strong> answers. Select at least one correct answer.</small>
    </p>
    <button type="submit" class="btn btn--radius btn-outline-success">Save</button>
    <a href="{% url 'quiz_change' quiz.pk %}" class="btn btn--radius btn--radius btn-outline-secondary" role="button">Nevermind</a>
    <a href="{% url 'question_delete' quiz.pk question.pk %}" class="btn btn--radius btn-outline-danger float-right">Delete</a>
  </form>
</div>
</div>
</body>
</html>
{% endblock %}

templates/teachers/question_delete_confirm.html
<!DOCTYPE html>
{% extends 'svapp/a&t.html' %}
{% load staticfiles %}
{% block body_block %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% include 'cdn.html' %}
    </head>
<body>
{% include 'messages.html' %}
<div class="container" style="margin-top:90px;">
  <div class="jumbotron">
  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the question <strong>"{{ question.text }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn--radius btn-outline-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'question_change' quiz.pk question.pk %}" class="btn btn--radius btn-outline-secondary btn-lg" role="button">Nevermind</a>
  </form>
</div>
</div>
</body>
</html>
{% endblock %}

templates/teachers/quiz_add_form.html
<!DOCTYPE html>
{% extends 'svapp/a&t.html' %}
{% load staticfiles %}
{% block body_block %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
      {% include 'cdn.html' %}
      </head>
<body>
{% include 'messages.html' %}
  <div class="container" style="margin-top:90px;">
    <h2 class="mb-3">Add a new Assessment</h2>
    <div class="jumbotron">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn--radius btn-outline-success">Save</button>
        <a href="{% url 'addquestions' %}" class="btn btn--radius btn-outline-secondary" role="button">Nevermind</a>
      </form>
    </div>
  </div>
</div>
</body>
</html>
{% endblock %}

templates/teachers/quiz_change_list.html
<!DOCTYPE html>
{% extends 'svapp/a&t.html' %}
{% load staticfiles %}
{% block body_block %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
  {% include 'cdn.html' %}
  </head>
<body>
{% include 'messages.html' %}

<div class="container" style="margin-bottom:100px;">
  <h2 style="margin-bottom:60px;">Assessments Results:</h2>
  <div class="row">
  {% for quiz in quizzes %}
  <div class="col-sm-6">
    <div class="card" style="margin-bottom:30px;">
      <div class="card-body">
        <h2 class="card-title" style="font-size:2.0rem; color:navy;"><a href="{% url 'quiz_change' quiz.pk %}">{{ quiz.name }}</a></h2>
        <h5 class="card-title">Subject: {{ quiz.subject.get_html_badge }}</h5>
        <h5 class="card-title">Questions: {{ quiz.questions_count }}</h5>
        <h5 class="card-title">Taken: {{ quiz.taken_count }}</h5>
      <div align="right">
        <a href="{% url 'quiz_results' quiz.pk %}" role="button" class="btn btn--radius btn-info btn-md">View results</a>
      </div>
      </div>
    </div>
  </div>
  {% empty %}
    <h2 class="bg-light text-center font-italic" colspan="5">You haven't created any Assessment yet.</h2>
  {% endfor %}
</div>
</div>
  </body>
</html>
{% endblock %}

templates/teachers/subject_details.html
<!DOCTYPE html>
{% extends 'svapp/a&t.html' %}
{% load staticfiles %}

{% block body_block %}
<section>
	<head>
		<title>Student Deatils</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	{% include 'cdn.html' %}
	</head>

	<body>
	  <div class="container" align='center' style="margin-bottom:70px; margin-top:60px;">
	  <h1 style="color:navy;"> Subjects Details</h1>
	  </div>

		<div class="container" style="margin-bottom:70px;">
	   <table class="table table-hover">
			 {% if subject_list %}
	     <thead align="center">
	       <tr>
					<th>Subject Name</th>
          <th>Subject Color</th>
					<th>Subject Update </th>
          <th>Subject Delete </th>
	       </tr>
	     </thead>

	     {% for subject in subject_list %}
	     <tbody style="text-transform: capitalize;" align="center">
	       <tr>
					 <td>{{subject.name}}</td>
           <td>{{subject.color}}</td>
					 <td>	<a class="btn btn--radius btn-outline-info btn-md" href="/subupdate/{{subject.id}}">Update</a> </td>
					 <td>	<a class="btn btn--radius btn-outline-secondary btn-md" href="/subdelete/{{subject.id}}">Delete</a> </td>
	       </tr>
	     </tbody>
	     {% endfor %}
			 {% else %}
			 <p>no subjects found</p>
			 {% endif %}

	   </table>
	 </div>
</body>
</section>
{% endblock %}